name: 'Send commits to Jira'
description: 'Parses a list of commit messages and sends the Jira ids to a Jira webhook.'
inputs:
  commits:
    description: 'An array containing a list of commit messages'
    required: true
  jira-webhook:
    description: 'The URL for the Jira webhook'
    required: true
outputs:
  raw-commits:
    description: 'The raw input of the commit messages'
  parsed-commits:
    description: 'The parsed commit messages from the input'
  jira-issue-keys:
    description: 'The JIRA issue keys parsed from the commit messages'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'git-branch'
  color: 'gray-dark'
